name: Build python wheels for all platforms

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build python wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
            ubuntu-latest,
            ubuntu-24.04-arm,
            macos-13,
            macos-latest,
            # windows-latest, # Needs a way to install the build dependencies (or VCPKG)
          ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.3

      - name: Install boost on macos
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-13'
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
        # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
          boost_version: 1.71.0
          platform_version: 10.15  #Using this to allow for older macos versions in the wheel
          
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
            
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl